I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 62, in script call
    call phone_call_test
  File "game/phone/definitions/01definitions.rpy", line 56, in script
    phone_koto "Hey!"
Exception: Sayer 'phone_koto' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 62, in script call
    call phone_call_test
  File "game/phone/definitions/01definitions.rpy", line 56, in script
    phone_koto "Hey!"
  File "C:\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'phone_koto' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Doki Doki Detective Club 1.1.2
Fri Sep 20 22:25:10 2024
