I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 256, in script
    show sayori 2v at 21
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 256, in script
    show sayori 2v at 21
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 754, in show
    img = i(img)
TypeError: 'int' object is not callable

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Doki Doki Detective Club 1.1.2
Sun Sep  8 20:04:17 2024
